export const TEST_ACTION_TYPE_REQUEST = 'TEST_ACTION_TYPE_REQUEST';
export const TEST_ACTION_TYPE = 'TEST_ACTION_TYPE';
export const ADD_NEW_GUEST = 'ADD_NEW_GUEST';
export const ADD_NEW_GUESTS_LIST = 'ADD_NEW_GUESTS_LIST';
