export const GET_GUESTS_REQUEST = 'GET_GUESTS_REQUEST';
export const UPDATE_WITH_DATA_FROM_DB = 'UPDATE_WITH_DATA_FROM_DB';

export const ADD_NEW_GUEST_REQUEST = 'ADD_NEW_GUEST_REQUEST';
export const ADD_NEW_GUEST = 'ADD_NEW_GUEST';
export const ADD_NEW_GUESTS_LIST = 'ADD_NEW_GUESTS_LIST';
export const ADD_NEW_GUESTS_LIST_REQUEST = 'ADD_NEW_GUESTS_LIST_REQUEST';

export const REMOVE_DATA_FROM_STORE_REQUEST = 'REMOVE_DATA_FROM_STORE_REQUEST';
export const REMOVE_DATA_FROM_STORE = 'REMOVE_DATA_FROM_STORE';
