export const GET_GUESTS_REQUEST = 'GET_GUESTS_REQUEST';
export const ADD_NEW_GUEST_REQUEST = 'ADD_NEW_GUEST_REQUEST';
export const ADD_NEW_GUEST = 'ADD_NEW_GUEST';
export const ADD_NEW_GUESTS_LIST = 'ADD_NEW_GUESTS_LIST';
